### ISSUE TITLE
Presentación del Servicio de Oferta de Servicios

### ISSUE THREAD

**Issue by yosbel-penate** [CreandoCuba/Web-Grupo-Creando-ID0019#30]
- [ ] Desarrollar una sección que presente de manera concisa y atractiva la información sobre el servicio, incluyendo un icono representativo.

**Comment by KevinPinoDelSol** [comment]
Movido al milestone de la parte estática de la aplicación porque los servicios siempre son los mismos. Luego subo la lista

**Comment by yosbel-penate** [comment]
ok, está bien, revisa la [discusión ](https://github.com/CreandoCuba/Web-Grupo-Creando-ID0019/discussions)ahí, dejé orientaciones
